[gcp_service_account]
type = "service_account"
project_id = "grading-system-470413"
private_key_id = "37235e6232c5a91913c9e1cd13e2368b6daddaf7"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCJTMF5uKCN8h35
DU2TS+Wz3BoWDVk0tQcq4KPs/rB9rVPI3tInMpK2kH2h3b5aAyGJNFvEUoYc/hON
kMWiS/GzNPXLvC5L/MmZhtWquwiRsSBPBwsmnHl1On4lhg4CpPXLaUZ+FVNjbo6a
FWuFVjxZXWtf3apljBtSDF8gl/T3sxfN96cJ9jH8GUWN6rcglyvjI+qCgA18ZACa
LLKs/ADUQHqF7uAVANRxNkol3dFGxNQovRLNgVL390DBYuGGn8j9+7ha4V8ZIZbB
O64xe/idP4fjp9TJdFXLUqZu3j31T+DpZE9usQa4Xr03gKdwe0weVE2gFOA9WEvm
e3F7MkahAgMBAAECggEAIIMjgY5dvp8px9MFnq6nSysApl4s1JVViCq/xpwc8PW9
VGCnRQ7tvPuENHNM4wXAyDu0y017YpwrxycUFbWEG5qb5c2+7NGEb62FJTO6+L0H
2I7jbhY5kK/0NTCEWs3zQmLAhZTJNU91xzjxSBa+na7IgV/9PKSrx4cUc6RoJstS
Og5KXj8Zh+iQKx7Knanvop+vbs9Pkq+GyXokCWPTjOTlN9hTNB7tDNCx41jtIXAT
9GUCrXTLMyctNLnBPjFUlnHkfKOT4tl2aChSHv0R13kRyHzP+w7t2AiDjejQF7eK
KFdniMQ7C08vmImgHE4Cjv0572uIG2NkIFhX8uAMUQKBgQC8QcsZQxqqcPKT23/0
3vQQBoY+MzRZFqkx6ACH+aG4bbx4BtoKpcGPJglybJ6EGdQaK0IlQeUNoyJLNt3U
wf56xCEXjGw7a290llvJ+B2uh58oX8bmb0o0vCnf21ZQNNOsEiObsQiG9fCsPCd8
vlaF7KBe/qjrl02kpN0vmDkKxQKBgQC6tMuAW1RZY0ukyS6aQ0cSvy6SfEjHUXiZ
/dLulKwrY4XF4NPBrn2F/rAWyWqULzac+4jETEIkkkXeIpArK8DIi/7nXgD/4BXH
8O3POD5SuCl/1oNodQFA/vRT
